# -*- coding: utf-8 -*-
"""Integrate GPS co-ordinate with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ku0_WvhFvh-SSxKY2hu6nf3i5hfSfPd2
"""

from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="myGeocoder")

# Get GPS coordinates for a given address
def get_coordinates(address):
    location = geolocator.geocode(address)
    return location.latitude, location.longitude

# Example usage:
address = "New York City, USA"
latitude, longitude = get_coordinates(address)
print(f"GPS coordinates for {address}: {latitude}, {longitude}")